# Generated by Django 3.2.5 on 2021-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210702_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cart_image',
            field=models.ImageField(upload_to='photos/categories'),
        ),
    ]
